<?php
/**
 * Testing worksheet — a structured tester checklist (single source of truth) covering every feature.
 * Rendered by the [sssj_tests] shortcode and the Settings → Testing tab. Keep suites() CURRENT on
 * every ship: when a feature changes, add/adjust its case here.
 *
 * @package Shuffles_SSJ
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Shuffles_SSJ_Tests {

	/**
	 * Test suites: each [ 'title', 'cases' => [ [ id, do, expect ], ... ] ]. Filterable.
	 *
	 * @return array
	 */
	public static function suites() {
		$s = array(
			array(
				'title' => __( 'Job ads & segregated boards', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove that jobs post correctly and that employee (TFN), contractor (ABN) and volunteer work stay strictly on their own boards. Goal: no engagement type ever leaks onto the wrong board, and anonymous/“open to” options behave.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'job-tfn', 'do' => __( 'As an advertiser, post a job with basis = TFN (employee).', 'shuffles-social-services-jobs' ), 'expect' => __( 'It shows on the Jobs board and the TFN board, and NEVER on the ABN board.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-abn', 'do' => __( 'Post a job with basis = ABN and a valid 11-digit ABN.', 'shuffles-social-services-jobs' ), 'expect' => __( 'ABN passes validation; it shows on the ABN board, never the TFN board. A bad ABN is rejected.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-vol', 'do' => __( 'Post a job with basis = Volunteer (no ABN). View the Volunteer board ([sssj_volunteer_board]), the TFN board and the ABN board.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It shows on the Volunteer board and the all-jobs board with a green “Volunteer” badge, and NEVER on the TFN or ABN boards. Any logged-in member can apply (no ABN required).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-anon', 'do' => __( 'Post a job linked to your organisation with “Advertise anonymously” ticked. View the job board, the job page source/structured data, and your organisation’s public profile “open positions”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The card shows “🕶️ Anonymous” with no org name/logo/tick; the JobPosting structured data shows “Private advertiser” (your name is not in SEO); and the role does NOT appear under your organisation’s public open positions.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'abr-record', 'do' => __( 'Set an ABR Web Services GUID in Settings → Compliance, then save an organisation (or worker) with a real ABN; reopen the form.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A read-only “Australian Business Register — recorded details” field shows the full register response: entity name, trading/business names, status, type, ACN, GST and location. The organisation’s public profile shows the same record. Without a GUID, nothing is recorded (offline checksum only).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'menu-repoint', 'do' => __( 'Open the header menu and click “My dashboard” and “Jobs”.', 'shuffles-social-services-jobs' ), 'expect' => __( '“My dashboard” lands on the all-in-one dashboard hub and “Jobs” lands on our jobs board (the page actually running the shortcode) — not a legacy/old page, even if one was previously mapped.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-search', 'do' => __( 'On the Jobs board, search a keyword and pick a category.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Results filter to matching jobs; the count updates.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'filter-ajax', 'do' => __( 'On any board (Jobs, Employee, Contractor, Worker, Organisations, Participant requests) change the search box, a filter, the radius, or click a pagination link.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Only the result tiles refresh in place (the Shuffles spinner shows briefly) — the whole page does NOT reload, the view does not jump to the top, and the cursor stays in the search box. The results map markers also refresh to match the filtered results (old pins clear, new pins plot, the map refits). The address bar still updates so the filtered view can be shared.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'smart-search', 'do' => __( 'On the Jobs (and Worker / Organisations) board, search a term using different words than the listing — e.g. “support work” for a “Disability Support Worker” role, “OT” for an occupational therapist, or “aged care” for a “home care” listing.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Related listings still appear — the search matches sector synonyms (broader, never narrower), so a sensible search does not come back empty.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-funding', 'do' => __( 'Set funding source(s) on a job (posting form), then on the Jobs board tick the funding chips (NDIS / Aged Care / DVA / …).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Results narrow to jobs matching the ticked funding (any of them); un-ticking widens again.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-radius', 'do' => __( 'Type a suburb in the location field and set a radius (with no Google key set).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Results narrow to jobs within the radius, nearest first (keyless geocoding).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-expire', 'do' => __( 'Set a job’s “Closes on” date in the past and wait for the daily cron (or run it).', 'shuffles-social-services-jobs' ), 'expect' => __( 'The job moves to draft and drops off the board.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-logo', 'do' => __( 'Attach a job to an organisation and leave its logo blank; then post another job and upload a logo.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The first job shows its organisation’s logo on the board card; the second shows its own uploaded logo (overrides the org’s).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'job-map', 'do' => __( 'Open a single job that has a location.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A Google map of the job’s suburb/town shows on the page (suburb level, no exact address). Works without a Google Maps API key.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Applying & messaging', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove candidates can apply (including the full employee/TFN flow) and that first contact runs through the safe internal relay. Goal: applications record once, screening answers reach the employer, and no email/phone is ever exposed.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'apply', 'do' => __( 'As a logged-in member, apply to a job with a cover note.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Application is recorded once (no duplicates); a message thread to the advertiser is started.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'apply-tfn', 'do' => __( 'Post a TFN (employee) job with a couple of screening questions and “Full pipeline”. As a candidate with a saved résumé, open that job and apply: pick a résumé, set availability + start date, answer the screening questions, and submit WITHOUT ticking right-to-work, then again WITH it ticked.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Without right-to-work it’s refused with a prompt; with it, the application saves. As the employer (My listings) the applicant shows the résumé link, availability, start date, right-to-work tick and the screening answers; the résumé opens for that employer only.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'apply-abn-gate', 'do' => __( 'Try to respond to a participant request / ABN task without a recorded ABN.', 'shuffles-social-services-jobs' ), 'expect' => __( 'You are blocked until a valid ABN is on file.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'msg-relay', 'do' => __( 'Open Messages, reply within a thread.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Reply sends; no email address is exposed; participants appear by pseudonym; non-parties can’t see the thread.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'app-status', 'do' => __( 'As the advertiser of a “Full pipeline” job, move an applicant New → Shortlisted → Interview → Offer → Hired in My listings, then open the applicant’s “Status history”. Compare with a job set to “Simple”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Full-pipeline jobs offer all stages (incl. Hired/Declined) and record a Status history; Simple jobs show only a minimal set. The applicant is emailed on each change.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'app-withdraw', 'do' => __( 'As the candidate, open My dashboard → My applications and click Withdraw on an active application.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The application is marked Withdrawn (and recorded in its history). Already-hired or already-withdrawn applications show no Withdraw button.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Workers', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove worker/contractor profiles, availability, visibility, résumés, travel radius and location search all behave. Goal: a worker is found exactly as widely as they choose — never more.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'worker-profile', 'do' => __( 'Create a worker profile; add Services via the search-and-add picker; set a location; choose visibility.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Profile saves; services show as pills; location geocodes; one profile per user.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-place-ac', 'do' => __( 'On the worker profile, start typing a suburb in “Your location” and pick a suggestion (needs a Google Maps API key set in Settings → Integrations).', 'shuffles-social-services-jobs' ), 'expect' => __( 'An autocomplete dropdown appears; picking a place fills Suburb / State / Postcode and records the lat/long, so the profile is found by location and radius.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'resume-store', 'do' => __( 'In My dashboard → “My résumés” (or [sssj_resumes]), upload a PDF/Word résumé, name it, tick “make default”; upload a second; set the other as default; remove one. Open a résumé’s file link while logged out / as another non-admin member.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Multiple résumés store and list with a Default badge; making one default unsets the other; removing works; the file link only opens for the owner or an admin (others get “Not allowed”). Only PDF/DOC/DOCX/RTF/ODT up to 8 MB are accepted, up to 5 résumés.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'asset-resume', 'do' => __( 'Open My dashboard → “Create an asset” (or the [sssj_create_asset] page) as a member with a worker profile. Switch between Résumé, Service flyer and Social post with the type selector (advertisers also get Job flyer, which lists your jobs to pick one); edit the headline and introduction and watch the preview update; read the readability check; then click Download PDF, Save image and Copy caption. Try it with no worker profile too.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Each type previews from your profile with your LOCATION in the header (résumé and flyer are one page; the social post is a square). Editing the headline/intro updates it live; the readability check flags anything missing (location, services, blurb length, a verified check). Download PDF opens the print dialog showing only the résumé; Save image downloads a PNG; Copy caption copies social text. With no profile, it prompts you to create one first.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'asset-render', 'do' => __( 'In Settings → Asset Rendering, leave it on “Browser” and open the résumé builder. Then set it to “Server”, enter your render service URL (e.g. a self-hosted Gotenberg at http://127.0.0.1:3000), tick self-hosted, save, click “Test connection”, and reopen the résumé builder.', 'shuffles-social-services-jobs' ), 'expect' => __( 'On “Browser” the builder shows a single “Download PDF” (browser print). On “Server” it shows “Print-quality PDF” (server) plus “Quick PDF (browser)”. “Test connection” reports success once the service is reachable; “Print-quality PDF” downloads a crisp server-rendered PDF of the résumé/flyer/job flyer. If the service is unreachable it shows an error and the browser path still works. Nothing breaks when no service is configured.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'board-place-map', 'do' => __( 'On the Jobs board, pick a location from the “Near a suburb…” autocomplete.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The results map recenters/zooms to that place and the result tiles refresh via AJAX to that area (a default radius is applied). No full-page reload.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-find', 'do' => __( 'On the Worker directory, search + tick “Available now” + set a location and radius.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Only available, in-radius workers show, nearest first.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-vis', 'do' => __( 'Set a worker profile to “Logged-in members”, then (a) view the directory as a guest and (b) open that profile’s direct web link as a guest.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It is hidden from guests in the directory; opening its direct link as a guest sends you to log in (it does not render), and logged-in members can view it. The owner and admins can always preview their own page.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'mask-rate', 'do' => __( 'On a worker profile (Privacy section) tick “Pay rate” as members-only and set a rate; then open the worker’s page and the directory while logged out, and again while logged in.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Logged out, the rate shows a “🔒 Log in to view” lock on both the profile and the card; logged in (or as the owner / an admin) the real rate shows. The profile still appears in the directory either way.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-photo', 'do' => __( 'Add a profile photo and a couple of gallery photos to a worker profile; save and open the worker’s page.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The headshot shows on the card and profile; gallery photos appear as a swipeable strip.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'media-guidance', 'do' => __( 'Open any form with a photo or logo upload (worker profile, organisation, post a job).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Each image field shows an “Image guide” with preferred dimensions and what makes good, valuable, consented content (no participant identification).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'media-video', 'do' => __( 'Paste a YouTube or Vimeo link into the “video” field on a worker, organisation or job, save, then open that single page. Also try pasting a non-YouTube/Vimeo URL.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A responsive video embed (privacy-friendly) appears under the listing. A link that is not YouTube or Vimeo is rejected and nothing is embedded.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-single', 'do' => __( 'Open a worker’s public profile page.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Full details render below the bio: availability, services, rate, location, languages/culture, verified checks and any custom fields (not a blank page).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-travel', 'do' => __( 'Set “How far are you willing to travel? (km)” on a worker profile and save.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The profile shows “Willing to travel: up to X km”, and the Jobs board defaults the radius to that distance for that worker.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'worker-hidden', 'do' => __( 'Set a worker profile to “Do not display”, then check the directory and the page source.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The profile is removed from the directory entirely and its page is noindex.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Participants (privacy-critical)', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove participant requests stay pseudonymous, suburb-level, members-only, admin-moderated and never indexed. Goal: the most vulnerable people on the platform are protected by design, not by setting.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'need-post', 'do' => __( 'Post a participant support request.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It is held for admin moderation; once approved it shows only a pseudonym + suburb — never a name or contact detail.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-gate', 'do' => __( 'Open the Participant requests board as a logged-out guest.', 'shuffles-social-services-jobs' ), 'expect' => __( 'You are prompted to log in; no requests are shown.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-noindex', 'do' => __( 'View the page source / robots of a participant request.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It is noindex and excluded from sitemaps.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-details', 'do' => __( 'On a participant request card, click “View full request”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The full request details expand in place (when, gender preference, full description) — no separate page, so privacy is preserved.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-seeking', 'do' => __( 'Post a participant request and choose “What are you seeking?” (ongoing support / one-off task / a provider).', 'shuffles-social-services-jobs' ), 'expect' => __( 'The choice is saved and shown as a badge on the request card (e.g. “Seeking a provider”).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-easyform', 'do' => __( 'Open the “Request a worker” form. Read it top to bottom.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It reads as clear numbered steps (What you need, Where, The kind of support, When and preferences, Close date) with friendly plain-English help, a single required field, and a reassuring intro about privacy and editing later.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-enddate', 'do' => __( 'Post a request and set (or leave) the “Close this request on” date; reopen the dashboard “My participant requests”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A close date is stored (about two months out if left blank), and the listing shows “Closes on …”.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'need-lifecycle', 'do' => __( 'Set a request’s close date in the past (or to within the reminder window) and run the daily cron; then open My dashboard and click “Reopen”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Within the window the owner gets a “closing soon” email; past the date the request auto-closes (moves to draft, drops off the board) and the owner gets a “now closed” email; “Reopen” republishes it with a fresh close date and resumes reminders.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Organisations', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove org profiles, categories, size/structure, NDIS + ABR data, teams (incl. request-to-join), sponsorship and the directory all work. Goal: organisations present accurately and reveal only what they intend.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'org-profile', 'do' => __( 'Create an org profile: logo, social links, sectors + funding (search-and-add), multiple locations.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Saves; logo + social icons + sector/funding pills appear on the profile and card.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-find', 'do' => __( 'On the Organisations directory, filter by sector, funding, location/radius, and “Only with open placements”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Results match all filters; multi-location orgs match if ANY site is in range.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'mask-org', 'do' => __( 'On an organisation profile (Privacy section) tick “Phone number” and/or “Website” as members-only; then open the org page while logged out and while logged in.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Logged out, the chosen field shows a “🔒 Log in” lock; logged in (or as the owner / an admin) the real phone / website button shows. NDIS-register details are never affected.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'team-add', 'do' => __( 'As an organisation owner, open the dashboard “Team” tab (or a page with [sssj_org_team]) and add a team member by the email or username of another existing account; try both “Member” and “Admin” roles. Then try an email with no account.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The existing person is added with the chosen role and appears in the roster. An unknown email is refused with a note to have them sign up first — no account is ever created.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'team-manage', 'do' => __( 'As an org admin, change a member’s role and then remove a member; also log in AS a promoted “Admin” member and confirm they can manage the team; finally try to remove or demote the owner.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Role changes and removals apply (removal only unlinks — the account still exists). An admin member can manage the team. The owner can never be removed or demoted.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'primary-role', 'do' => __( 'In My dashboard → My roles, tick a couple of hats, set a “Primary role”, and save. Reopen the dashboard and the [sssj_menu].', 'shuffles-social-services-jobs' ), 'expect' => __( 'The dashboard opens to the primary role’s tab; the menu shows that role’s items with a “See all” dropdown revealing the rest. Setting “No preference” shows everything (no See-all).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'team-join', 'do' => __( 'As a different logged-in member, open an organisation’s profile and click “Request to join” (add a message). Then, as that org’s admin, open My dashboard → Team and Approve (or Decline) the request.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The requester sees “Request to join pending” (and can cancel). The admin sees it under “Requests to join” with a count on the Team tab; Approve adds them to the team (as Member or Admin), Decline removes it. Nobody joins without admin approval.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-counters', 'do' => __( 'Check an org card’s counters.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Shows current open jobs and total placed (all-time Offers).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-jobs', 'do' => __( 'Attach a job to an org, open the org page.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The org page lists its open positions (browse jobs by company) + Organization structured data.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-hidden', 'do' => __( 'Tick “Do not display” on an org profile, then check the Organisations directory, the page source, and open the org’s direct web link as a non-member.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The org drops off the directory, is excluded from the sitemap, and its page is noindex with no Organization structured data. Opening its direct link as a non-member returns “not found”; only its own team and site admins can view it.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-ndis', 'do' => __( 'On an org profile tick “We are a registered NDIS provider” and enter a registration number.', 'shuffles-social-services-jobs' ), 'expect' => __( 'An “🛡️ NDIS Registered · #number” badge links to the NDIS Commission register on the card + profile; status/groups show when set (admin or auto-scan hook).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-seed-fields', 'do' => __( 'Settings → Profile Fields → “Add recommended provider fields”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A Shuffles-style organisation field set is added (specialisations, Services Provided, service delivery, ages supported, accepting clients, accessibility, languages, years operating, accreditations, Peak Bodies); the banner-flagged ones (incl. Services Provided + Peak Bodies) become filters on the Organisations directory and appear on org profiles. Re-running only adds fields that don’t already exist.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-autofill', 'do' => __( 'On the organisation form enter your website URL and click “Fetch details from my website”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Empty name / description / phone fields are pre-filled from your site for review (only empty fields are touched).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-category', 'do' => __( 'On the organisation form choose an “Organisation type” (Support provider / Supplier / SDA-housing / Real estate / Professional services / Other) and save; then filter the Organisations directory by that type.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The category saves, shows as a badge on the card + profile, and the “All organisation types” directory filter narrows to it.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-sponsored', 'do' => __( 'As an admin, edit an organisation and tick “Sponsored placement” in the Verification box; view the directory.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The org sorts to the top of the directory and shows a “★ Sponsored” badge on its card + profile; un-ticking removes both. (Admin-only — members can’t self-set it.)', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'open-to', 'do' => __( 'On a job, tick “Open to overseas applicants / visa sponsorship” and “Accepts work-placement enquiries”. On an organisation, tick those plus “Volunteers welcome”. View the job board, job page, organisations directory and org profile.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The chosen options show as badges (✈️ Visa sponsorship, 🎓 Work placements, 🤝 Volunteers welcome) on the relevant cards and profiles.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Compliance & verification', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove credential uploads, the admin verification queue, the ✓ Verified / blue-tick badges, and the live ABN (ABR) + NDIS register checks. Goal: a trust badge is only ever granted by an admin against real evidence — never self-claimed — and register data stays read-only.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'cred-upload', 'do' => __( 'As a worker, add a credential (e.g. WWCC) with an evidence PDF.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Saved as Pending; the evidence file has no public URL.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cred-verify', 'do' => __( 'As an admin, open Jobs & Engagements → Verification, view the evidence, Approve it.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The worker gains the ✓ Verified badge (and the verified checks show on their card).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cred-serve', 'do' => __( 'Copy an evidence link and open it while logged out (or as a different non-admin).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Access is denied — only the owner or an admin can open it.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cred-expire', 'do' => __( 'Set a verified credential’s expiry in the past; run the daily cron.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It expires, the badge drops, and a reminder email is sent.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'blue-tick', 'do' => __( 'As an admin, edit a worker or organisation, tick “Account verified (blue tick)” in the Verification box and update; then view the directory and profile.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A blue tick shows next to the name on cards and the profile (and on jobs from a verified org). Un-ticking removes it. It is separate from the green ✓ Verified credential badge.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'abr-check', 'do' => __( 'Enter an ABR GUID (Settings → Compliance), then post a job (ABN basis) or organisation with a valid ABN.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The ABN is checked against the Australian Business Register on save; the card/profile shows an “🏢 ABR Active · <Entity Name>” badge. Without a GUID, only the offline checksum runs.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'org-abn-required', 'do' => __( 'Try to save an organisation profile without an ABN (or with an invalid one).', 'shuffles-social-services-jobs' ), 'expect' => __( 'It is rejected — organisations (non-TFN businesses) require a valid 11-digit ABN. TFN job ads never ask for an ABN.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-lookup', 'do' => __( 'Edit a registered organisation, enter its NDIS Registration No (the number after ?id= in its provider-register URL, e.g. 902439) and save; then view the org profile.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A “NDIS provider registration” table shows the live Registration status, the approved registration groups and the “in force until” date, with a link to the Commission register and a “Last checked” date. (Reads the NDIS Commission’s own public listing.)', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-rescan', 'do' => __( 'As an admin, open that org profile and click “Re-check NDIS register now”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The branded Shuffles spinner shows briefly, then the table refreshes from the live listing. The monthly background check (Settings → Compliance toggle) re-reads every registered org and emails the change-alert address only when status, groups, or the expiry date change — never the provider.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-soletrader', 'do' => __( 'On a worker profile, tick “I’m an NDIS-registered sole trader” and enter the NDIS Registration No (e.g. 902439); save, then view the worker’s public profile.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The same NDIS registration table (status, groups, expiry, register link, last checked) shows on the individual’s profile, and the listing is included in the monthly auto-check.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-scannow', 'do' => __( 'On the organisation or worker form, type an NDIS Registration No and click “Scan now”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The Shuffles spinner shows, then the live legal name, status, ABN, head office, website, registration groups and expiry appear inline — without saving the form. A bad number shows a friendly error.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-abn-mismatch', 'do' => __( 'Enter an ABN on the form that differs from the ABN on the NDIS listing, then Scan now (or save and view the profile).', 'shuffles-social-services-jobs' ), 'expect' => __( 'A red warning note appears saying the register ABN differs from the ABN on file.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-outlets', 'do' => __( 'Scan a registered provider that lists outlets (e.g. 902439).', 'shuffles-social-services-jobs' ), 'expect' => __( 'The outlets and their phone number(s) appear (read from the register footer); these are read-only and have no editable field.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ndis-revoked-red', 'do' => __( 'Scan a provider whose status is Revoked/Banned (or set the stored status to “Revoked”).', 'shuffles-social-services-jobs' ), 'expect' => __( 'The status badge shows on a RED background, not green — on both the profile table and the Scan-now preview.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'spinner', 'do' => __( 'Save an organisation or worker profile, and use the website “Fetch details” button.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A branded Shuffles spinner (site logo if set, else a blue ring) overlays the form while the few-second lookups run.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Monetisation', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the paid gates (posting volume, featured placement, directory listing, responding) apply only when monetisation is switched on. Goal: the site is never locked by default, and participants always post free.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'mon-off', 'do' => __( 'With monetisation OFF, post jobs and respond.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Everything is free / ungated.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'mon-cap', 'do' => __( 'Turn monetisation ON; set a free-listing cap; post beyond it without a subscription.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Posting is blocked with an upgrade prompt; a subscriber posts unlimited + gets featured placement.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'mon-participant-free', 'do' => __( 'Turn monetisation ON, then as a member whose role is Participant (only) post a direct job for a worker.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Posting is allowed free — participants employing directly or seeking workers/providers are never charged, even when monetisation is on. (A participant who is also a provider follows the provider rules.)', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'mon-directory-fee', 'do' => __( 'Turn monetisation ON, then save an organisation as a member with no advertiser/provider subscription, and view the Organisations directory.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The org is not listed in the directory until the provider holds a listing subscription (or is an admin); with monetisation OFF every org lists for free.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'ads-integration', 'do' => __( 'With the Advanced Ads plugin active, create a placement, map it to a slot in Settings → Ads (e.g. Board — top), and put [sssj_ad placement="…"] on a page. Then deactivate Advanced Ads (or turn off Settings → Ads) and reload.', 'shuffles-social-services-jobs' ), 'expect' => __( 'When Advanced Ads is active + enabled, the banner shows in the board slot and via the shortcode (labelled “Advertisement”); when it is inactive or the master switch is off, nothing renders and no errors appear (standalone-safe).', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Hats / roles & onboarding', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove hats grant the right abilities, onboarding routes new members, the dashboard reveals by hat, and the primary-role focus + “See all” work. Goal: members see what’s relevant to them, with everything still reachable.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'roles-pick', 'do' => __( 'Put [sssj_roles] on a page (or open the “My roles” tab in [sssj_dashboard]); as a logged-in member tick hats from the grouped picker (I offer work / I’m looking for work / I need support) — e.g. Employer/company AND Available for contracting — and save.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Hats save (confirmation shows), persist on reload, and the matching capabilities are granted (employer → post jobs + org; contractor → worker profile).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'roles-dashboard', 'do' => __( 'After setting hats, reopen the dashboard.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The dashboard reveals only the sections matching your hats — an employer sees My listings & applicants + Post a job / organisation; a contractor sees My profile + Matched jobs + Credentials; a member with both sees both, in one place. A member with no hats yet still sees everything (capability fallback).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'roles-guest', 'do' => __( 'Open the [sssj_roles] page while logged out.', 'shuffles-social-services-jobs' ), 'expect' => __( 'You are prompted to log in; no role form is shown.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'onboard', 'do' => __( 'Put [sssj_onboard] on a “Get started” page; as a new member tick some hats and Continue.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Hats save, then tailored next-step buttons appear (set up profile / create organisation / post a job / request support / go to dashboard) matching the chosen hats.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'onboard-affiliate', 'do' => __( 'With FluentAffiliate active (or an Affiliate URL set in Settings → Monetisation), open [sssj_onboard] as a member with the Participant hat; then turn the affiliate promo off and reload.', 'shuffles-social-services-jobs' ), 'expect' => __( 'An “Earn money by referring others” card appears (extra encouragement for participants), clearly states a PayPal account is needed and that it can be set up later, and links out to the affiliate sign-up (new tab) without blocking onboarding. With FluentAffiliate inactive / promo off, no card shows and nothing breaks. The same card is available via [sssj_affiliate].', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'provider-size', 'do' => __( 'Edit an organisation, set a Size + Legal structure, save; then open the Organisations directory and use the “Any size” / “Any structure” filters.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The size + structure show as badges on the card/profile and filter the directory (e.g. Size = Sole trader narrows to sole traders).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'sole-trader-dir', 'do' => __( 'As a member with the contractor hat, create an organisation/provider listing.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It defaults to size = Sole trader and appears in the Organisations/Providers directory (filterable as Sole trader) alongside your worker profile.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Accessibility / CALD + appearance', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the accessibility / multilingual (CALD) tools and the theming (Style Studio) work. Goal: the platform is usable by everyone — including low-vision, neurodiverse and non-English speakers — and stays on-brand.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'cald-lang', 'do' => __( 'Switch the language in the toolbar.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Tagged UI labels translate; right-to-left languages flip layout; the choice persists site-wide.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cald-english', 'do' => __( 'While in another language, hit the “English Hot Key”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The interface returns to English (button shows only when not in English).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cald-modes', 'do' => __( 'Toggle High contrast / No colour / Larger text / Read aloud / Voice input.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Each mode applies and persists; modals are not trapped.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cald-langpill', 'do' => __( 'Look at the language picker in the accessibility bar.', 'shuffles-social-services-jobs' ), 'expect' => __( 'It is a compact rounded pill sized to its text (not a full-width box), matching the other accessibility controls.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'studio', 'do' => __( 'In Settings → Appearance, change colours and a preset; watch the live preview; Save.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Preview updates live; saved styles apply on the front end; the theme is untouched.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Navigation, selects & responsive', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the login-aware menu (+ admin Settings sub-item + Appearance-menu sync), the searchable pill selects, and the responsive layout. Goal: navigation and inputs work cleanly on every device.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'menu', 'do' => __( 'View [sssj_menu] logged out, then logged in.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Logged-out shows browse + Log in/Register; logged-in shows dashboard/messages/log out + capability links.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'auto-menu', 'do' => __( 'In Settings → General, tick “Show navigation menu at the top of every page”, save, and open any front-end page.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The navigation bar appears at the very top of every page; un-ticking removes it.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'dashboard', 'do' => __( 'Put [sssj_dashboard] on a page; view it logged in as a worker, then as an advertiser.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A tabbed hub shows only relevant tabs (Overview always; My listings for advertisers; Matched jobs + Credentials for workers; Saved searches; Messages). Tabs switch panels; with JS off all sections still show.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'pills', 'do' => __( 'Open any form/filter with a dropdown or multi-pick.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Single selects are searchable; multi-picks show removable pills (no bare checkbox grids).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'dynamic-filter', 'do' => __( 'On any directory, change a category, tick a chip or drag the radius — without clicking any button.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Results update automatically (no “Filter” button needed). Typing in the search box updates shortly after you stop.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'clear-all', 'do' => __( 'With several filters applied, click “Clear all”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Every filter resets and the full list returns.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'use-my-location', 'do' => __( 'Click “Use my location” next to the location field and allow the browser prompt.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A default radius is applied and results re-sort to nearest first; denying access shows a friendly message.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'distance-pill', 'do' => __( 'Search any directory with a location (type a suburb or use my location).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Each result card shows a highlighted “X km away” pill (nearest location for organisations).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'map-markers', 'do' => __( 'With a Google Maps API key set, single-click a map marker, then double-click it.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Single click opens an info box (summary + View link); double click scrolls to that result’s card and surrounds it with an animated rainbow “tracer” highlight.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'mobile', 'do' => __( 'Open the boards, directories and forms on a phone (or a narrow window).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Filter controls stack full-width, cards go single-column, nothing overflows; it looks professional.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'readme', 'do' => __( 'On each directory, click “Read me — things to know”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A collapsible note opens with tips specific to that directory (jobs / workers / organisations / participant requests); click again to close.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Custom profile fields & CRM sync', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove admin-defined custom fields (incl. banner filters) and the FluentCRM tag/list sync behave. Goal: extra fields and CRM stay in step without exposing private data or naming the AI/search vendor.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'field-add', 'do' => __( 'In Settings → Profile Fields, add a multi-select field (e.g. “Programs” with options NDIS, Aged Care, DVA), shown on Workers.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The field is listed; on the worker profile form it appears as a searchable multi-select pill picker and saves.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'field-banner', 'do' => __( 'Tick “show on banner filters” for a select field; edit and delete a field.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Edit pre-fills the form; delete removes the field (saved values are untouched).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'field-filter', 'do' => __( 'With a banner-filter select field set, give two workers different values, then use that filter on the worker directory.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The directory shows a searchable “All <field>” filter; choosing a value narrows results to matching profiles; “Clear all” resets it. Works on the worker, organisation and participant-request directories.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'crm-map', 'do' => __( 'In Settings → CRM Sync, enable sync, then map a value (e.g. Funding: NDIS) to a FluentCRM tag and/or list.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The tag/list pickers list your FluentCRM tags & lists (searchable); the mapping saves.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'crm-apply', 'do' => __( 'As a member, choose that mapped value on your profile and save; then un-choose it and save.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Choosing attaches the mapped tag/list to your FluentCRM contact; un-choosing removes it. Each change shows in the per-user log (Users → edit, and Settings → CRM Sync).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'crm-missing', 'do' => __( 'Delete a mapped tag in FluentCRM, then save a profile that uses it.', 'shuffles-social-services-jobs' ), 'expect' => __( 'An admin alert appears (and a “missing” log entry) so you can re-point the mapping; nothing breaks the save.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Front-page display & animations', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the marketing blocks render and animate: hero (multi-button), counters, featured (with teaser), recent, Why-us (grid/carousel/font) and Join. Goal: the public front end looks right and funnels people in.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'disp-hero', 'do' => __( 'Put [sssj_hero title="…" button_text="Browse jobs" button_url="/jobs" button2_text="Find a worker" button2_url="/find-a-worker" button3_text="Request support" button3_url="/request-support"] on a page.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A gradient hero banner fades in with the headline, up to FOUR call-to-action buttons (first = primary, rest = outline), and a “🛡️ Safety, built in” strip. safety="off" hides the strip.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-stats', 'do' => __( 'Add [sssj_stats] and scroll it into view; then try [sssj_stats min="25"].', 'shuffles-social-services-jobs' ), 'expect' => __( 'The counters animate up to the live totals. With min="25", any counter below 25 is hidden until the real total reaches it (so small early numbers stay hidden).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-recent', 'do' => __( 'Add [sssj_recent type="jobs" count="6"] and [sssj_recent type="orgs" layout="list"].', 'shuffles-social-services-jobs' ), 'expect' => __( 'Recent cards reveal with a staggered fade; list layout is a compact sidebar list. Participant requests only show to logged-in members.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-featured', 'do' => __( 'Add [sssj_featured]. Promote a job (mark it featured), give it a description, and reload.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Featured roles show with a subtle shine and a short ~40-character teaser from the role’s description under the rate; with none promoted it falls back to the newest jobs.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-whyus', 'do' => __( 'Create a page via Settings → Pages → “Why us (benefits)” (or put [sssj_why_us] on a page) and open it. Then try [sssj_why_us layout="carousel" per_row="3"], [sssj_why_us per_row="2" rows="2"], and font="brand".', 'shuffles-social-services-jobs' ), 'expect' => __( 'A point-form benefits list renders, each with an icon, heading and blurb. layout="carousel" gives a horizontal AUTO-scrolling row (3 in view) that pauses on hover/touch with no visible scrollbar; per_row/rows control columns and how many show; font="theme" (default) matches the page font, font="brand" uses the plugin font. The default heading shows “Why ” + your site name. Grids collapse to one column on mobile.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'whyus-edit', 'do' => __( 'In Settings → Pages → “Why us — benefit points”, edit a line (icon | Heading | Blurb), add a new line, save, then reload the Why us page. Then clear the box entirely and save.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The Why us page reflects your edited/added points in order. Clearing the box restores the built-in default points.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-join', 'do' => __( 'Create a page via Settings → Pages → “Join (welcome / get started)” (or put [sssj_join] on a page) and open it logged out.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A welcome page shows a “Let’s get you onboarded” button (to the onboarding page), Create-account + Log-in buttons, and quick links to browse jobs / find a worker / organisations.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-hero-quotes', 'do' => __( 'Put [sssj_hero] with four button pairs (button_text/url … button4_text/url) into a page in the block editor and view it.', 'shuffles-social-services-jobs' ), 'expect' => __( 'All four buttons appear (not just the first) — the editor’s smart-quote curling no longer breaks the later attributes.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'hero-blurb', 'do' => __( 'In Settings → Pages → “Home page hero”, set a Hero headline and a Hero main blurb, save, then view a page with a plain [sssj_hero] (no title/subtitle attributes). Then clear both fields and reload.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The hero uses your edited headline and blurb without changing the shortcode. Clearing them falls back to the focus-programs line, then the built-in default. A title/subtitle on the shortcode still overrides the settings.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'feature-today', 'do' => __( 'Put [sssj_feature_today] on a page (or drop the “Today’s feature spotlight” Elementor widget in a full-width section). Click “Learn more about this feature”, then the Pause control, then double-tap the tile. Reload on two different days, and behind a full-page cache.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A full-width tile titled “Today’s Highlighted Site Feature” shows one feature with a short summary. “Learn more” expands an inline “how it works” explanation right on the tile (it does NOT link to the marketing doc or anywhere). A ball of light traces the outside border; tap to stop/start, double-tap to reverse. The feature changes the next day and stays correct even behind a full-page cache (it refreshes from the REST endpoint).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'promo-studio', 'do' => __( 'As an admin, put [sssj_promo] on a private page and open it. Click “Show another” a few times, pick a different highlight from the dropdown, then click “Save image” and “Copy caption”. Open the same page logged out / as a normal member.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A square branded graphic shows one highlight at a time — built from real platform numbers (only those big enough to impress) and the same brand messages as the daily feature spotlight, never any participant data. “Show another” / the dropdown swap the graphic AND its caption together; “Save image” downloads a square PNG; “Copy caption” copies the matching words + hashtags. Non-admins see only an “available to administrators” notice.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'disp-motion', 'do' => __( 'Turn on the OS “reduce motion” setting and reload.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Animations are disabled — content appears immediately with final numbers.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'elementor', 'do' => __( 'With Elementor active, edit a page and open the “Shuffles Jobs” widget category; drag in Hero / Stats / Featured / Recent / Menu and set their controls.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Each widget renders the matching block with your settings, both in the editor preview and on the live page.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Email alerts', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove opt-in alerts (job matches, new candidates, saved-search digests) — including the logged-out “Save & alert me” login prompt. Goal: members only ever get alerts they asked for.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'alert-worker', 'do' => __( 'On a worker profile tick “Email me when new jobs match my profile”, then (Settings → Email Alerts) click “Run alerts now” after a matching job is posted.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The worker receives an email digest of new matching jobs. Nothing is sent if they did not opt in.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'alert-advertiser', 'do' => __( 'When posting a job tick “Email me when new candidates match this job”; add a matching worker, then run alerts.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The advertiser receives an email digest of new matching candidates.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'alert-saved', 'do' => __( 'On a directory, set a filter and click “Save & alert me”; add a new matching listing, then run alerts. Manage via [sssj_saved_searches].', 'shuffles-social-services-jobs' ), 'expect' => __( 'The search is saved; an email arrives with new matching listings; Remove deletes the saved search.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'alert-guest', 'do' => __( 'Log out, set a filter on a board, and click the “🔔 Save & alert me (log in)” button.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The button is visible to logged-out visitors but isn’t active — it sends you to log in and returns to the same filtered search, where you can then save it. No alert is saved while logged out.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'alert-master', 'do' => __( 'Turn the master “Enable email alerts” off and run alerts.', 'shuffles-social-services-jobs' ), 'expect' => __( 'No emails are sent; opt-ins are remembered for when it is turned back on.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Smart matching', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the matcher surfaces relevant workers on a job, relevant jobs on a worker, and the synonym-aware search. Goal: the right people see the right opportunities, with clear reasons.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'match-job', 'do' => __( 'Open a job that has a service category and a location.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A “Workers who may suit this role” panel lists ranked workers, each with a short reason (shared services, distance, available, has ABN).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'match-worker', 'do' => __( 'Open a worker profile that has services + a location.', 'shuffles-social-services-jobs' ), 'expect' => __( 'An “Open roles this worker may suit” panel lists ranked jobs with reasons.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'match-me', 'do' => __( 'As a logged-in worker, put [sssj_matches] on a page.', 'shuffles-social-services-jobs' ), 'expect' => __( '“Jobs matched to you” lists ranked jobs for your profile; logged-out or no-profile shows a prompt.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'match-abn', 'do' => __( 'Compare matches for an ABN job vs a TFN job.', 'shuffles-social-services-jobs' ), 'expect' => __( 'ABN-holding workers rank above those without an ABN for the ABN role; the basis is noted in the reasons.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Guides, workflows & policies', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the in-app advice guides, the step-by-step end-user workflows, and the plain-English policy summaries all render and self-heal their links. Goal: members can self-serve clear, sector-appropriate help — “how to do it well” (Guides), “the exact steps” (How it works) and “the rules that keep it safe” (Policies).', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'guides-show', 'do' => __( 'Put [sssj_guides] on a page (or open Settings → Guides) and click each guide header.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The advice guides show (write a job post, respond to a job, ABN contractor, standing profile, flyer/résumé best-practice); the first is open; clicking expands/collapses each.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'guides-only', 'do' => __( 'Use [sssj_guides only="respond-to-job"].', 'shuffles-social-services-jobs' ), 'expect' => __( 'Only the chosen guide renders.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'flows-show', 'do' => __( 'Put [sssj_workflows] on a page (or open Settings → How-to Workflows) and click each workflow header.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The eleven explainer workflows show (set up account, advertise a role, apply for a TFN job, quote for ABN work, review applicants, request support, store a résumé, join an org, save alerts, volunteer, stay safe); each has a Goal, “Before you start”, numbered steps with location hints, a “Done” line; the first is open and headers expand/collapse.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'flows-start', 'do' => __( 'In a workflow, click its “Start here” button (e.g. “Post a job →” or “Browse employee jobs →”).', 'shuffles-social-services-jobs' ), 'expect' => __( 'It lands on the page that actually runs that shortcode (self-healing link); if no such page exists yet, the button is simply hidden rather than dead.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'flows-foryou', 'do' => __( 'Log in as a member with a primary role set (e.g. Participant), then open the [sssj_workflows] page.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Workflows for that role (e.g. “Ask for support privately”) float to the top with a “For you” badge; everything else still appears below (nothing is hidden).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'flows-filter', 'do' => __( 'Use [sssj_workflows only="apply-tfn,build-resume"] and, separately, [sssj_workflows roles="contractor"].', 'shuffles-social-services-jobs' ), 'expect' => __( 'The first shows only those two workflows; the second shows only workflows tagged for contractors.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'flows-nav', 'do' => __( 'Create the “How it works” page (Settings → Pages → How it works → Create), then view the [sssj_menu] / header menu.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A “How it works” item appears in the navigation (and in the synced Appearance menu after the next version re-sync), pointing at the workflows page.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'policies-show', 'do' => __( 'Put [sssj_policies] on a page (or open Settings → Policies) and click each policy header.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Eleven plain-English policies show (Complaints, Privacy, NDIS Code of Conduct, Incident Management, Safeguarding, Terms, Worker Screening, Data Retention, Cookies, Inclusion, Advertising & media); the first is open; each has a summary + key points; the footer lists NDIS/OAIC/AHRC + interpreter contacts.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'policies-only', 'do' => __( 'Use [sssj_policies only="privacy,complaints"].', 'shuffles-social-services-jobs' ), 'expect' => __( 'Only the chosen policies render. The full formal templates remain in /docs for adoption.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'policy-advertising', 'do' => __( 'Open the “Advertising & media production” policy (in [sssj_policies] or its /docs template).', 'shuffles-social-services-jobs' ), 'expect' => __( 'It states we prefer not to use children (with safeguards if one must appear), that anyone in commercial media is paid fairly, and that written informed consent (including any agreed remuneration) is obtained, with truthful, inclusive content that never identifies a participant.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'marketing-page', 'do' => __( 'Open Settings → Marketing, create the Marketing page, and view it (or put [sssj_marketing] on a page).', 'shuffles-social-services-jobs' ), 'expect' => __( 'The marketing master renders as a readable page (positioning, business logic, functional spec, audience analysis), generated from docs/MARKETING-MASTER.md, naming no third-party tools.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Reviews & ratings', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove members can rate and review contractors (workers) and providers (orgs), that only genuinely-engaged members can review, that nothing shows until an admin approves, and that the average feeds trust. Goal: ratings are real, moderated and fair — never gameable.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'review-gate', 'do' => __( 'As a member who has NOT messaged or applied to a given worker/org, open that profile and look for the review form. Then start a message thread (or apply) and reload.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Before any engagement there is no review form (just a note that only engaged members can review); after a relay message/application exists between you, the “Leave a review” form appears. You can never review your own profile/org.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'review-submit', 'do' => __( 'Leave a 1–5 star rating + title + review and submit; reload the profile while logged in as someone else (or logged out).', 'shuffles-social-services-jobs' ), 'expect' => __( 'You see “Awaiting moderation”; the review does NOT yet appear publicly. The star widget records your rating; one (editable) review per member per subject.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'review-moderate', 'do' => __( 'In Settings → Reviews & Ratings, Approve the pending review (then try Reject on another).', 'shuffles-social-services-jobs' ), 'expect' => __( 'Approved reviews appear on the profile and count toward the average + count; rejected ones never show. The average/count update immediately.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'review-respond', 'do' => __( 'As the reviewed worker (or an org admin), open your profile and use “Respond to this review”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Your single public response shows under that review; non-owners do not see the respond form.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'review-trust', 'do' => __( 'Approve some reviews for a worker, then view “Jobs matched to you” / the worker matches on a job.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A well-rated worker scores a little higher and shows a “Rated X★” reason — the approved average feeds the matching trust signal.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'review-off', 'do' => __( 'Turn off “Enable reviews & ratings” in Settings → Reviews & Ratings and reload a profile.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The reviews section disappears everywhere and no new reviews can be left; existing reviews are retained for when it is re-enabled.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'testi-submit', 'do' => __( 'On a worker/provider profile, open “What people say” → “Leave a testimonial” as a logged-in non-owner. Write an endorsement, choose how you are credited + your relationship, submit.', 'shuffles-social-services-jobs' ), 'expect' => __( 'You see “your testimonial was sent for moderation”; it does NOT appear publicly yet. You are never required to use your full name. Owners do not see the submit form on their own profile.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'testi-owner', 'do' => __( 'As the profile owner, open “What people say” → “Manage my testimonials”. Add a quote you received; after an admin approves, click “Feature”, then “Hide”, then “Delete”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Owner-added quotes are also held for moderation. Only Approved testimonials can be Featured; only Approved + Featured ones show publicly under “What people say”. Hide/Delete work as labelled.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'testi-moderate', 'do' => __( 'In Settings → Testimonials, Approve a pending testimonial (try Reject and Delete on others). Then turn off “Enable testimonials” and reload a profile.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Approve makes it available to feature; Reject/Delete keep it off the profile (Reject also un-features it). With testimonials disabled, the “What people say” section disappears everywhere and no new ones can be left; existing ones are kept.', 'shuffles-social-services-jobs' ) ),
				),
			),
			array(
				'title' => __( 'Dashboard & operations', 'shuffles-social-services-jobs' ),
				'objective' => __( 'Prove the all-in-one dashboard hub, scheduled (cron) jobs, demo users + “View as”, and admin operations. Goal: members and admins can run everything from one place, and background jobs report their status.', 'shuffles-social-services-jobs' ),
				'cases' => array(
					array( 'id' => 'dash-profile', 'do' => __( 'Open [sssj_dashboard] as a logged-in member and click the “My profile” tab.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Your personal worker/candidate profile editor is embedded right there, with buttons to manage an organisation or a participant support request, and a tip pointing to the “My roles” tab.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'dash-earn-support', 'do' => __( 'Open [sssj_dashboard] with the referral program available (and, separately, with the support portal available). Look at the tab row.', 'shuffles-social-services-jobs' ), 'expect' => __( 'An “Earn” tab appears when referrals are available (showing the referral promo with the PayPal note, plus the referral dashboard) and a “Support” tab appears when a support portal is available (showing it inline). Neither tab appears when its capability is absent, and nothing breaks.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'form-enhance', 'do' => __( 'Open the Create worker profile page and scroll/fill it in.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Fields are grouped into titled section cards (each with a tasteful left accent border); a completeness meter updates as you fill fields; the “available for work” checkbox shows as a pill toggle (and still submits); the About box has a character counter; file buttons are styled and the profile photo previews; a sticky Save bar appears on scroll; Ctrl+S saves; the tab title shows a ● when there are unsaved changes. Tom Select pickers, the suburb autocomplete, NDIS “Scan now” and form submission all still work.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'swipe', 'do' => __( 'Put [sssj_swipe] on a page; swipe/drag the top card right and left, use the ✕/♥/↺ buttons and the ← → arrow keys.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Providers show one card at a time; right saves to your shortlist (toast confirms; stored when logged in), left skips, ↺ / U undoes; tapping “View profile” opens the org page; when the deck empties a shortlist summary shows.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cron-tab', 'do' => __( 'As an admin, open Settings → Cron Job List & Status.', 'shuffles-social-services-jobs' ), 'expect' => __( 'Every plugin background job is listed (daily maintenance, daily email alerts, monthly NDIS check) with its frequency, last run, next run due and status. “Run now” triggers a job; after the monthly NDIS check the row shows e.g. “12 checked, 1 could not be read”.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'cron-status', 'do' => __( 'Click “Run now” on a job, then reload the tab.', 'shuffles-social-services-jobs' ), 'expect' => __( 'The “Last run” time updates and Status shows “Completed OK”. A job that starts but fatals mid-run would instead show “Did not complete”.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'provider-import-preview', 'do' => __( 'Settings → Provider Import (beta): choose “Active providers”, upload the NDIS CSV, Upload & preview.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A preview shows the row count, the auto-detected column mapping and a sample of parsed rows — with NOTHING written (proof of concept is preview-only; no organisations are created).', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'logic-tab', 'do' => __( 'Open Settings → Business Logic.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A plain-English list of the plugin’s business rules renders (roles, ABN/TFN, who pays, verification, NDIS, privacy, matching) plus a numbered “Key invariants (never rules)” list.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'menu-editprofile', 'do' => __( 'Put [sssj_menu] on a page and view it logged in.', 'shuffles-social-services-jobs' ), 'expect' => __( 'An “Edit my profile” link appears (opening the worker/candidate profile editor); it is absent when logged out.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'menu-admin-settings', 'do' => __( 'View [sssj_menu] as an administrator and hover/focus “My dashboard”.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A “Settings” sub-item drops down (links to the plugin settings page). Non-admins never see it.', 'shuffles-social-services-jobs' ) ),
					array( 'id' => 'nav-sync', 'do' => __( 'Settings → Pages → “Header menu” → Create header menu; then open Appearance → Menus.', 'shuffles-social-services-jobs' ), 'expect' => __( 'A “Jobs & Engagements” menu exists with the public items (Jobs, Find a worker, Organisations, Participant requests, Post a job, My dashboard, Log in, Register). Re-syncing after a change keeps it current; menu items you add by hand are left untouched.', 'shuffles-social-services-jobs' ) ),
				),
			),
		);
		return apply_filters( 'shuffles_ssj_test_suites', $s );
	}

	/** Total number of test cases. */
	public static function count_cases() {
		$n = 0;
		foreach ( self::suites() as $suite ) {
			$n += count( $suite['cases'] );
		}
		return $n;
	}

	/**
	 * Render the interactive worksheet (progress saved per browser via localStorage).
	 *
	 * @param array $atts title (optional), version (optional).
	 * @return string
	 */
	public static function render( $atts = array() ) {
		$title   = ! empty( $atts['title'] ) ? $atts['title'] : __( 'Testing worksheet', 'shuffles-social-services-jobs' );
		$version = defined( 'SHUFFLES_SSJ_VERSION' ) ? SHUFFLES_SSJ_VERSION : '';
		ob_start();
		?>
		<div class="sssj sssj--tests" data-sssj-tests data-tests-version="<?php echo esc_attr( $version ); ?>">
			<div class="sssj-panel">
				<h2 style="margin-top:0"><?php echo esc_html( $title ); ?> <?php if ( $version ) : ?><span class="sssj-badge"><?php echo esc_html( 'v' . $version ); ?></span><?php endif; ?></h2>
				<p class="description"><?php esc_html_e( 'Give this to a tester. Checks are grouped by area, and each group states its overall objective so you know what it’s proving. Work through each case, mark Pass or Fail. Progress is saved in your browser; use Print for a paper copy or a PDF.', 'shuffles-social-services-jobs' ); ?></p>
				<div class="sssj-tests__bar">
					<strong data-tests-progress>0 / <?php echo esc_html( (string) self::count_cases() ); ?></strong>
					<span class="sssj-tests__track"><span class="sssj-tests__fill" data-tests-fill></span></span>
					<button type="button" class="sssj-btn sssj-btn--ghost sssj-btn--sm" data-tests-reset><?php esc_html_e( 'Reset', 'shuffles-social-services-jobs' ); ?></button>
					<button type="button" class="sssj-btn sssj-btn--secondary sssj-btn--sm" onclick="window.print()"><?php esc_html_e( 'Print', 'shuffles-social-services-jobs' ); ?></button>
				</div>
			</div>
			<?php foreach ( self::suites() as $suite ) : ?>
				<div class="sssj-panel">
					<h3 style="margin-top:0"><?php echo esc_html( $suite['title'] ); ?> <span class="sssj-badge sssj-badge--sm"><?php echo esc_html( sprintf( _n( '%d check', '%d checks', count( $suite['cases'] ), 'shuffles-social-services-jobs' ), count( $suite['cases'] ) ) ); ?></span></h3>
					<?php if ( ! empty( $suite['objective'] ) ) : ?>
						<p class="sssj-tests__obj"><strong><?php esc_html_e( 'Objective:', 'shuffles-social-services-jobs' ); ?></strong> <?php echo esc_html( $suite['objective'] ); ?></p>
					<?php endif; ?>
					<table class="sssj-tests__table">
						<?php foreach ( $suite['cases'] as $c ) : ?>
							<tr data-test-id="<?php echo esc_attr( $c['id'] ); ?>">
								<td class="sssj-tests__do">
									<strong><?php echo esc_html( $c['do'] ); ?></strong>
									<div class="sssj-tests__expect"><?php echo esc_html__( 'Expected:', 'shuffles-social-services-jobs' ) . ' ' . esc_html( $c['expect'] ); ?></div>
								</td>
								<td class="sssj-tests__marks">
									<button type="button" class="sssj-btn sssj-btn--sm sssj-tests__pass" data-mark="pass"><?php esc_html_e( 'Pass', 'shuffles-social-services-jobs' ); ?></button>
									<button type="button" class="sssj-btn sssj-btn--sm sssj-tests__fail" data-mark="fail"><?php esc_html_e( 'Fail', 'shuffles-social-services-jobs' ); ?></button>
								</td>
							</tr>
						<?php endforeach; ?>
					</table>
				</div>
			<?php endforeach; ?>
		</div>
		<?php
		return ob_get_clean();
	}
}
